---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  roles:
    - homebrew_tap
    - homebrew
    - homebrew_cask
    - zsh
    - anyenv
    - rbenv
    - ndenv
    - osx_defaults
