---
- name: install ndenv via anyenv
  shell: anyenv install ndenv
  args:
    creates: ~/.anyenv/envs/ndenv/bin/ndenv

- name: install node
  shell: ndenv install {{ version }}
  args:
    creates: ~/.anyenv/envs/ndenv/versions/{{ version }}
  with_items: "{{ node_versions }}"
  loop_control:
    loop_var: version
  when: node_versions is defined

- name: ndenv rehash
  shell: ndenv rehash
  changed_when: False
