---
- name: install cask packages
  homebrew_cask:
    name="{{ item.name }}"
    state="{{ item.state | default('installed')}}"
  with_items:
    - { name: docker }
    - { name: docker-toolbox }
    - { name: firefox-esr }
    - { name: iterm2 }
    - { name: google-chrome }
    - { name: kitematic }
    - { name: microsoft-office }
    - { name: skitch }
    - { name: vagrant }
    - { name: virtualbox}
    - { name: visual-studio-code }
    - { name: dropbox }
    - { name: appcleaner }
    - { name: bettertouchtool }
    - { name: hyper }
    - { name: font-fira-code }
    - { name: minikube }
    - { name: the-unarchiver }

  become: yes
  failed_when: False
