---
- name: install rbenv via anyenv
  shell: anyenv install rbenv
  args:
    creates: ~/.anyenv/envs/rbenv/bin/rbenv

- name: install ruby
  shell: env MAKE_OPTS="-j 4" rbenv install {{ version }}
  args:
    creates: ~/.anyenv/envs/rbenv/versions/{{ version }}
  with_items: "{{ ruby_versions }}"
  loop_control:
    loop_var: version
  when: ruby_versions is defined

- name: rbenv rehash
  shell: rbenv rehash
  changed_when: False
